In [36]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [37]:
data = {
    "areas": [2000,3000,3200,3600,4000],
    "bedrooms":[3.0,4.0, " ", 3.0, 5.0],
    "age":[20,15,18,30,8],
    "price":[550000,565000,610000,595000,760000],
}

In [38]:
df = pd.DataFrame(data)

In [39]:
df["bedrooms"]= df["bedrooms"].replace(" ", float("nan"))

In [40]:
df

   areas  bedrooms  age   price
0   2000       3.0   20  550000
1   3000       4.0   15  565000
2   3200       NaN   18  610000
3   3600       3.0   30  595000
4   4000       5.0    8  760000

In [41]:
import math
median_bedrooms = math.floor(df.bedrooms.median())

In [42]:
median_bedrooms

3

In [43]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [44]:
df.bedrooms

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [45]:
df

   areas  bedrooms  age   price
0   2000       3.0   20  550000
1   3000       4.0   15  565000
2   3200       3.0   18  610000
3   3600       3.0   30  595000
4   4000       5.0    8  760000

In [46]:
reg = linear_model.LinearRegression()

In [49]:
reg.fit(df[['areas','bedrooms','age']],df.price)

LinearRegression()

In [50]:
reg.coef_

array([   72.19170404,  6410.31390135, -4523.5426009 ])

In [51]:
reg.intercept_

447125.5605380708

In [53]:
reg.predict([[3000,3,40]])

C:\New folder\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([501989.9103139])

In [54]:
reg.predict([[4000,6,50]])

C:\New folder\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([548177.13004486])

In [55]:
72.19170404*4000 + 6410.31390135*6 - 4523.5426009*50 + 447125.5605380708

548177.1300611708

In [56]:
reg.predict([[2000,3,20]])

C:\New folder\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([520269.05829595])