In [1]:
import pandas as pd

data = {
    'day': ["1/1/2017", "1/2/2017", "1/4/2017", "1/5/2017", "1/6/2017", "1/7/2017"],
    'temperature': [32, 35, 28, "", 32, ""],
    'windspeed': [6, 7, 2, '', 23, ""],
    'event': ["Rain", "Sunny", "Snow", "", "Cloudy", ""],
}

# Create the DataFrame
df = pd.DataFrame(data)

# Replace empty strings with NaN
df = df.replace("", float("nan"))

print(df)

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0    Rain
1  1/2/2017         35.0        7.0   Sunny
2  1/4/2017         28.0        2.0    Snow
3  1/5/2017          NaN        NaN     NaN
4  1/6/2017         32.0       23.0  Cloudy
5  1/7/2017          NaN        NaN     NaN

In [2]:
df.fillna(0)

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0    Rain
1  1/2/2017         35.0        7.0   Sunny
2  1/4/2017         28.0        2.0    Snow
3  1/5/2017          0.0        0.0       0
4  1/6/2017         32.0       23.0  Cloudy
5  1/7/2017          0.0        0.0       0

In [3]:
new_df = df.fillna({
    'temperature':0,
    'windspeed':0,
    'event': "no event"
})

In [4]:
new_df

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017         35.0        7.0     Sunny
2  1/4/2017         28.0        2.0      Snow
3  1/5/2017          0.0        0.0  no event
4  1/6/2017         32.0       23.0    Cloudy
5  1/7/2017          0.0        0.0  no event

In [6]:
new_df = df.fillna(method = "bfill")
new_df

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0    Rain
1  1/2/2017         35.0        7.0   Sunny
2  1/4/2017         28.0        2.0    Snow
3  1/5/2017         32.0       23.0  Cloudy
4  1/6/2017         32.0       23.0  Cloudy
5  1/7/2017          NaN        NaN     NaN

In [7]:
new_df = df.fillna(method = "ffill")
new_df

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0    Rain
1  1/2/2017         35.0        7.0   Sunny
2  1/4/2017         28.0        2.0    Snow
3  1/5/2017         28.0        2.0    Snow
4  1/6/2017         32.0       23.0  Cloudy
5  1/7/2017         32.0       23.0  Cloudy

In [8]:
new_df = df.fillna(method = "ffill", limit = 1)
new_df

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0    Rain
1  1/2/2017         35.0        7.0   Sunny
2  1/4/2017         28.0        2.0    Snow
3  1/5/2017         28.0        2.0    Snow
4  1/6/2017         32.0       23.0  Cloudy
5  1/7/2017         32.0       23.0  Cloudy

In [9]:
new_df = df.interpolate()

In [10]:
new_df

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0    Rain
1  1/2/2017         35.0        7.0   Sunny
2  1/4/2017         28.0        2.0    Snow
3  1/5/2017         30.0       12.5     NaN
4  1/6/2017         32.0       23.0  Cloudy
5  1/7/2017         32.0       23.0     NaN

In [11]:
new_df = df.dropna()

In [12]:
new_df

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0    Rain
1  1/2/2017         35.0        7.0   Sunny
2  1/4/2017         28.0        2.0    Snow
4  1/6/2017         32.0       23.0  Cloudy

In [13]:
new_df = df.dropna(how = "all")

In [14]:
new_df

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0    Rain
1  1/2/2017         35.0        7.0   Sunny
2  1/4/2017         28.0        2.0    Snow
3  1/5/2017          NaN        NaN     NaN
4  1/6/2017         32.0       23.0  Cloudy
5  1/7/2017          NaN        NaN     NaN

In [17]:
dt = pd.date_range("01-01-2017", "01-6-2017")
idx = pd.DatetimeIndex(dt)
df = dt.reindex(idx)
df

(DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
                '2017-01-05', '2017-01-06'],
               dtype='datetime64[ns]', freq='D'),
 None)