In [3]:
import pandas as pd

In [4]:
data = {
    'day':["1/1/2017","1/2/2017","1/3/2017"],
    'temperature':[32,35,28],
    'windspeed':[6,7,2],
    'event':["Rain","Sunny","Snow"],

}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
#to import data from the csv
df = pd.read_csv("weather.csv")

#to import data from the excel
df = pd.read_excel("weather.xlsx")

In [7]:
dfs = pd.DataFrame(df, columns=["day","temperature","windspeed","event"])
dfs

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [8]:
data = [
    {'day':'1/1/2017','temperature':35,'windspeed':34,'event':'Rainy'},
    {'day':'1/1/2017','temperature':35,'windspeed':34,'event':'Rainy'}

]

In [10]:
datas = pd.DataFrame(data)

In [11]:
datas

        day  temperature  windspeed  event
0  1/1/2017           35         34  Rainy
1  1/1/2017           35         34  Rainy