In [1]:
import pandas as pd

In [12]:
data = {
    'day':["1/1/2017","1/2/2017","1/3/2017","1/4/2017","1/5/2017","1/6/2017"],
    'temperature':[32,35,28,24,32,32],
    'windspeed':[6,7,2,7,4,2],
    'event':["Rain","Sunny","Snow","Snow","Rain","Sunny"],
}

In [13]:
df = pd.DataFrame(data)

In [14]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [16]:
#to get the shape of the our data
# df.shape
rows, column = df.shape

In [17]:
column

4

In [18]:
#provides first 5 datas
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [19]:
df.head(2)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [20]:
#provides last 5 data
df.tail()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [21]:
df.tail(1)

        day  temperature  windspeed  event
5  1/6/2017           32          2  Sunny

In [22]:
#Provides the data from 2 to 5
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [25]:
# provides the columns of dataset
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [26]:
#Provides specifically
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [27]:
#Provides the event 
df['event']

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [28]:
#provides the type of the data
type(df['event'])

pandas.core.series.Series

In [29]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [30]:
#Gives the data of what you have specified in inside of df
df[['event','day']]

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

In [32]:
df[['event','day','temperature']]

   event       day  temperature
0   Rain  1/1/2017           32
1  Sunny  1/2/2017           35
2   Snow  1/3/2017           28
3   Snow  1/4/2017           24
4   Rain  1/5/2017           32
5  Sunny  1/6/2017           32

In [33]:
df['temperature']

0    32
1    35
2    28
3    24
4    32
5    32
Name: temperature, dtype: int64

In [34]:
df.temperature

0    32
1    35
2    28
3    24
4    32
5    32
Name: temperature, dtype: int64

In [35]:
#Provides the max value of it
df['temperature'].max()

35

In [36]:
#Provides the min value of it
df['temperature'].min()

24

In [37]:
#Provides the standard deviation value of it
df['temperature'].std()

3.8858718455450894

In [38]:
#Provides the each and everything value of data
df['temperature'].describe()

count     6.000000
mean     30.500000
std       3.885872
min      24.000000
25%      29.000000
50%      32.000000
75%      32.000000
max      35.000000
Name: temperature, dtype: float64

In [39]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [40]:
#Provides the value greater than 32 of temperature
df[df.temperature>=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [41]:
df[df.temperature == df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [42]:
df[df.temperature == df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [43]:
df['day'][df.temperature == df.temperature.max()]

1    1/2/2017
Name: day, dtype: object

In [46]:
df[['day','temperature']][df.temperature == df.temperature.max()]

        day  temperature
1  1/2/2017           35

In [47]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [48]:
#Provides the staring and ending index
df.index

RangeIndex(start=0, stop=6, step=1)

In [51]:
#to remove the sno and make the day as the sno
# and inplace makes it default change
df.set_index('day',inplace = True)

In [52]:
#Provides the data of all the column
df.loc['1/4/2017']

temperature      24
windspeed         7
event          Snow
Name: 1/4/2017, dtype: object

In [54]:
df.reset_index(inplace = True)

In [55]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [56]:
df.set_index('event',inplace = True)

In [57]:
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           32          2

In [59]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7